CREATE TABLE IF NOT EXISTS endereco (
  cod_endereco INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  cep VARCHAR(8) NOT NULL,
  logradouro VARCHAR(100) NOT NULL,
  complemento VARCHAR(100),
  bairro VARCHAR(100) NOT NULL,
  cidade VARCHAR(100) NOT NULL,
  uf VARCHAR(2) NOT NULL);